// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdFNl04r8FF0-LyHBUhip_n_AIABKmoxw',
    appId: '1:10059288829:android:f506eeb70767f3cb4fae94',
    messagingSenderId: '10059288829',
    projectId: 'tablets-519a0',
    storageBucket: 'tablets-519a0.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0mLO4QjR10H92fO0ZnbWJBQEpqC8Z-wU',
    appId: '1:10059288829:web:34f0585f74ee57574fae94',
    messagingSenderId: '10059288829',
    projectId: 'tablets-519a0',
    authDomain: 'tablets-519a0.firebaseapp.com',
    storageBucket: 'tablets-519a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0s6M7BvhRMLieDAiB0a6I9jTHegEFTz0',
    appId: '1:10059288829:ios:88f2193af4b470f44fae94',
    messagingSenderId: '10059288829',
    projectId: 'tablets-519a0',
    storageBucket: 'tablets-519a0.appspot.com',
    iosBundleId: 'com.tablets.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0mLO4QjR10H92fO0ZnbWJBQEpqC8Z-wU',
    appId: '1:10059288829:web:6340e4b18fd41bba4fae94',
    messagingSenderId: '10059288829',
    projectId: 'tablets-519a0',
    authDomain: 'tablets-519a0.firebaseapp.com',
    storageBucket: 'tablets-519a0.appspot.com',
  );

}